# -*- coding: utf-8 -*-
"""BreakandContunie.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ke6ExZ8jlt6ge3aLREpZJF2lwPHAdlt8
"""

print("Break and Contunie")

for x in range(1,11):
  if x ==8:
    break

  print(x)
print("\n Broke out of loop at x = ", x)