# -*- coding: utf-8 -*-
"""counterControlledRepetition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w_w8lf-VysfABFwYjQVmeZTi0qO5RtAs
"""

print("Counter Controlled Repetition")

total =0
gradeCounter =1

while gradeCounter <= 10 :
  grade = input("Enter grade")
  grade = int(grade)
  total = total + grade
  gradeCounter = gradeCounter + 1

average = total /10
print("Class average is", average)