# -*- coding: utf-8 -*-
"""forStucture.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15PwTCAw3YvN_hZI8EyCbeb_5NAnE8kz0
"""

print("for stucture")

for counter in range(10):
  print(counter)

sum = 0
for number in range(2,101,2):
  sum += number
  print("sum is", sum)