# -*- coding: utf-8 -*-
"""kalkulator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sze1AvdzmGumMzDY6BZeIu9Au5BAqkzF
"""

print("Prograqam Kalkulator Sederhana")

print('Selamat datang di program kalkolator sederhana')
print('pilih 1 untuk perkalian')
print("pilih 2 untuk penjumlahan")
print('pilih 3 untuk pengurangan')
print('pilih 4 untuk pembagian')

pilihan = input("masukan pilihan anda :")

angka1 = int(input("Masukan angka pertama "))

angka2 = int(input("masukan angka kedua "))

if (pilihan == "1"):
  print(angka1 * angka2)
elif (pilihan == "2"):
  print(angka1 + angka2)
elif (pilihan == "3"):
  print(angka1 - angka2)
else:
  print(angka1 / angka2)