# -*- coding: utf-8 -*-
"""logicalOperator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eRvwqgHqwXz1FAzxq-r0_CrUOgFoZns-
"""

print("Logical operator")



if gender == “female” and age >= 65:
  seniorfemales = seniorfemales + 1
if iq > 250 or iq < 20:
  strangevalues = strangevalues + 1
if not found_what_we_need:
  print("didn’t find item") 
  
  # NB: can also use !=if i != j:print “Different values”