# -*- coding: utf-8 -*-
"""modulInputOutpotExpection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ihBL9cxzVqRt0LabozL-2rKMqu2NM1kn
"""

#Model
#modul  adalah  file  yang  terdiri  dari  kode  Python.  
#Modul  dapat mendefinisikan fungsi, kelas dan variabel. 
#Modul juga bisa menyertakan kode yang bisa dijalankan “runable”.

def print_func( par ): 
  print("Halo : ", par) 
  return

nama = "bima"
print_func(nama)

#input statement
nama =input("Siapa nama kamu: ") 
umur =input("Berapa umur kamu: ") 

print("Hello",nama,"umur kamu adalah",umur,"tahun")

#OUTPUT
nama = "ProgrammerhandalD3TI"
print("Hello", nama)
print(" ")
nama ="ProgrammerhandalD3TI"
print("Hello"+ nama)

#Menggunkan Format
nama_mu = input("Nama kamu: ") 
nama_dia =input("Nama dia: ") 
print("{} dengan {} sepertinya pasangan yang serasi :)".format(nama_mu, nama_dia))

#Exception handling
#File Not Found Eror

filename = "pacar.txt"
try :
  my_file = open(filename)
  print(my_file.read())
  my_file.close()
except:
  print(filename, "tidak ditemukan")

#Exception handling
#ZeroDivisionErrors

angka1 = int(input("Masukan angka pertama : "))
angka2 = int(input("Masukan angka kedua : "))

try:
  pembagian = angka1 /angka2
  print(pembagian)

except ZeroDivisionError:
  print("Tidak boleh dibagi dengan 0")