# -*- coding: utf-8 -*-
"""nomor2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15QZFd8wxz_jax3rLDb3Bc8g0YKxLRYE4
"""

print("Nomor dua")

if 0:
    print("0 is true")
else:
    print("0 is false")

if 1:
     print("non-zero is true")

if -1:
    print("non-zero is true")