# -*- coding: utf-8 -*-
"""pembandingNilai.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NWwacf8HBcPY26zk7yXvCk6o5zAZCGL3
"""

print("Program pembanding nilai")

nilai1 = int(input("Masukan nilai pertama "))

nilai2 = int(input("Masukan nilai kedua "))

#percabangan
if(nilai1 > nilai2):
  print("nilai pertama lebih besar dari nilai kedua")
elif(nilai1 < nilai2):
  print("nilai kedua lebih besar dari nilai pertama")
else:
  print("nilainya sama")