# -*- coding: utf-8 -*-
"""percabangan1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ORCQEVPIiuilonOolD0sq1_P2SLQ5enx
"""

print("Percabangan 1")

# get price from user and convert it into a float:
price = float(input("Enter the price of one tomato: "))
if price < 1:
  s = "That’s cheap, buy a lot!"
elif price < 3:
  s = "Okay, buy a few"
else:
  s = "Too much, buy some carrots instead"

print(s)