# -*- coding: utf-8 -*-
"""programPangkat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RoIbHnsDaJZrOOwdd--Sz9PPmDRP97gu
"""

print("Program penjumlahan pangkat dalam akar")

a = int(input("Masukan nilai pertama "))

print(a)

b = int (input("Masukan nilai kedua "))

c = (a**2) + (b**2)

akar = (c**1/2)
print(akar)