# -*- coding: utf-8 -*-
"""sentinelControlledRepetition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b2r4v83TF8RTufZt810CMWp-xTX34N0s
"""

print("Sentinel-Controlled Repetition")

#initialization phase
total = 0 #sum of grade
gradeCounter = 0 #number of grades entered

#processing phase
grade = input("Enter grade, -1 to end: ")
grade = int(grade)

while grade != 1:
  total = total + grade
  gradeCounter = gradeCounter + 1 
  grade = input( "Enter grade, -1 to end: ") 
  grade = int( grade )

#termination phase
if gradeCounter != 0:
  average = float(total) / gradeCounter
  print("Class average is", average)
else:
  print("No grades were entered")